In [ ]:
import numpy as np

pip install numpy
conda install numpy 

Vectors, the 1D Arrays

Matrices, the 2D Arrays

3D and above Multidimensional arrays

In [ ]:
array1 = numpy.array([1,2,3,4,5])
array1
type(array1)

In [ ]:
array1 = np.array([1,2,3,4,5])
array1

In [ ]:
np.__version__

In [ ]:
# ndarray.ndim : specifies the number of dimensions
#ndarrray.shape: what is the dimension of the array
# ndarray.size : number of elements 
#ndarray.dtype : tell u the datatype of the elements
a1=np.array(1) 
a1.ndim

In [ ]:
array1 = np.array([1,2,3,4,5])
array1.ndim

In [ ]:
a2=np.array([[1,2,3],[6,7,8,9,10]])


In [ ]:
a2=np.array([[1,2,3],[6,7,8,9,10]])
a2

In [ ]:
a3=np.array([[[1,2],[3,4],[5,6]]])
a3.ndim
a3

In [ ]:
a4 = np.arange(2,12,2)
a4

In [ ]:
a5=np.linspace(2,12,6)
a5

In [ ]:
a5=np.array([(1,2,3,4),(5,6,7,8)], dtype = float)
a5

In [ ]:
type(2.3)

In [ ]:
a= np.array ([20,30,40,50])
b= np.arange(4)
c=a-b
print(a)
print(b)
print(c)

In [ ]:
b**2

In [ ]:
 np.sin(a) * 100

In [ ]:
a<35

In [ ]:
A = np.array ([[1,1],[0,1]])
B = np.array ([[2,0],[3,4]])
print(A)
print(B)

In [ ]:
A * B

In [ ]:
A @ B

In [ ]:
A.dot(B)

In [ ]:
list1 = []
print("Enter 10 elements to create a NumPy array")
for i in range(12mm):
    list1.append(input())
array = np.array(list1)
print("Created array is :",array)

In [ ]:
array2= array . reshape(2,6)
array2

In [ ]:
newarr = np.append(array2, [['3'],['4']], axis = 1)
newarr

In [ ]:
#Append a new row
len = newarr[0].size
len
list1 = []
print("Enter elements to create a NumPy array")
for i in range(len):
    list1.append(input())

In [ ]:
row=np.array(list1)
newarr1 = np.append(newarr, [row], axis = 0)
newarr1

In [ ]:
# Count the number of elements along a x axis and y axis 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.size(arr, axis =0))
print(np.size(arr, axis =1))


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr.shape)
for x in np.nditer(arr):
  print(x)

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis =1 )
print(arr)

In [ ]:
arr = np.vstack((arr1, arr2))
print(arr)


In [ ]:
arr = np.hstack((arr1, arr2))
print(arr)

In [ ]:
np.zeros((2,5))


In [ ]:
np.ones(5, dtype = np.int32)

In [ ]:
a = np.array([[1,2,3],
[4,5,6]])
a
b = np.transpose (a)
b

In [ ]:
a = np.array([1,2,3,4,5,6])
print(a[1:6:2])

In [ ]:
a = np.array([[1,2,3],
[4,5,6]])
print(a[0,0])
print(a[0:1,1:3 ])


In [ ]:
a = np.array([[[1,2],[3,4],[5,6]],# first axis array
[[7,8],[9,10],[11,12]],# second axis array
[[13,14],[15,16],[17,18]]])# third axis array
a

In [ ]:
a[1: , 0:2, 0:2].flatten()

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a[::-1, ::-1 ])

In [ ]:
a = np.array([1,2,3,4,5,6])
print('Subtract :',a-5)
print('Multiply :',a*5)
print('Divide :',a/5)
print('Power :',a**2)
print('Remainder :',a%5)

In [ ]:
a = np.arange(5,15,2)
a
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

In [ ]:
a = np.array([[1,6,5],
[4,3,7]])
print (np.min(a))

print('Min :',np.min(a,axis=0))

print('Max :',np.max(a,axis=1))

In [ ]:
a = np.array([1,2,3,4,5,6])
newarr = np.array_split(a, 3)
newarr


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 5)

print(newarr)

In [ ]:
a = np.array([1,2,3,4,5,4,4])
x=np.where(a%2==1)
print(x)

In [ ]:
arr = np.array([6,7,8,9])
x= np.searchsorted(arr,10)
x

In [ ]:
a = np.array ([2,1,4,3,5,6,9,7,8])
print(np.sort(a))

In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

In [ ]:
#Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....
np.arange(0,100,2)


In [ ]:
#From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match
a=np.array([1,2,3,4])
b=np.array([1,9,3,7])
x=np.where(a==b)
print(x)

In [ ]:
#Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive)
a= np.linspace(0,100,5)
a

In [ ]:
#Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5
a= np. ones((2,3),dtype=int)
a
b= 5*a
b

In [ ]:
#Convert a 1-D array to a 3-D array
a = np.arange(0,12)
a
b=a.reshape(2,2,3)
b

In [ ]:
#Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
a= np.arange(100,200,10)
b=a.reshape(5,2)
b

Following is the provided numPy array. Return array of items by taking the third column from all rows

[[11 22 33]

 [44 55 66]

 [77 88 99]]

Printing array of items in the third column from all rows

[33 66 99]


In [ ]:
a=np.array([[11,22,33],[44,55,66],[77,88,99]])
newa= a[:, 2]
newa

#Return array of odd rows and even columns from below numpy array

Printing Input Array

[[ 3  6  9 12]

 [15 18 21 24]

 [27 30 33 36]

 [39 42 45 48]

 [51 54 57 60]]

Printing array of odd rows and even columns
[[ 6 12]

 [30 36]

 [54 60]]

In [ ]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
sampleArray
newa= sampleArray[::2, 1::2]


In [ ]:
# Split the array into four equal-sized sub-arrays.
#Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1
# and then Split the array into four equal-sized sub-arrays.

Sort following NumPy array

Case 1: Sort array by the second row

Case 2: Sort the array by the second column

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

In [162]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
sortArrayByRow = sampleArray[:,sampleArray[1,:].argsort()]
sortArrayByRow

sortArrayByColumn = sampleArray[sampleArray[:,1].argsort()]
sortArrayByColumn

array([[82, 22, 12],
       [34, 43, 73],
       [53, 94, 66]])

Delete the second column from a given array and insert the following new column in its place.

[[34 43 73]

 [82 22 12]

 [53 94 66]]


In [164]:
print("Printing Original array")
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]
